---
title: "01_Mars_Shape_Phylo_Prep"
author: "Vera Weisbecker"
date: "26 June 2019"
output: html_document
---


## load required packages

```{r }
library(geomorph)
library(abind)

```

## Read in coordinates


```{r }

filelist <- list.files(path= "../Data/Raw/Coordinates", pattern = "*.txt")

#Next step is to remove the Museum IDs from the specimen names   
  
  tmp <- matrix(unlist(strsplit(filelist, "_")),ncol=3,byrow = TRUE)   

  filelist_species <- paste(tmp[,1], tmp[,2], sep="_")

  
  names <- gsub (".txt", "", filelist) # extracts names of specimens from the file name
  filelist <- paste("../Data/Raw/Coordinates/", filelist, sep="") # rename with path
  coords <- NULL # make empty object that will be filled with 3D array of coordinate data
  for (i in 1:length(filelist)){
    temp  <- read.morphologika(filelist[i]) 
    k <- dim(temp)[1] 
    coords <- rbind(coords, two.d.array(temp)) }
  Data <- arrayspecs(coords, k, 3) 
  dimnames(Data)[[3]] <- filelist_species
  remove(i, filelist, names, k, coords, temp) # clean up environment
  
  
```

#Read in classifier file that contains the species name, locomotion type, diet, and clade; and also read in a ply file for checks


```{r}

speclist<- read.delim("../Data/Raw/Trial_classifier_list.txt")
rownames(speclist) <-speclist$Specimen

#This is a mesh I crunched down to 500,000 faces. It's 18 kb.
Apyg <- read.ply("../Data/Raw/Acrobates_pygmaeus_J7579.ply")

#There's a weird thing about these meshes at the moment, they show up as black. So to fix this I found a strange workaround - but any improvements are much appreciated

Apyg$material$color <- Apyg$it
Apyg$material$color <- "hotpink"

#Isn't she gorgeous!!
shade3d(Apyg)


```

#Now you want to check if all is well

````{r}

#Double check that the order of your Array and the order of your specimen list are the same (they will need to talk to each other!). This has to return "TRUE" for all. 

dimnames(Data)[[3]]==rownames(speclist)


#Double check that the 3D info is entered properly by checking landmark numbers
  plot3d(Data[,,4], asp=FALSE)
  text3d(Data[,,4], texts=c(1:58))
  

#open new 3D window so any previous don't accidentally superimpose  
open3d()
#There's a way of getting rid of those lines but I forgot it.
plotspec(Apyg, Data[,,1], ptsize=2, lwd=0 )


````



#GPA for all coordinates

```{r}
#Run GPA
GPA <- gpagen(Data)

```
#run a basic PCA
```{r}

PCA <- plotTangentSpace(GPA$coords)

plotRefToTarget(PCA$pc.shapes$PC1min, PCA$pc.shapes$PC1max, method="vector")

plot(PCA$pc.scores[,1]~ log(GPA$Csize))


```



#Package into RDA file so it's available in the analyses
```{r}

save.image(file="../Data/Processed/Read_in_Data")




```

